#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

PATH=$PATH:$HOME/.local/bin/statusbar

picom -f &
dunst &	# dunst for notifications
dwmblocks &
mpd &
feh --randomize --bg-fill ~/images/leftbg/* --randomize --bg-fill ~/images/rightbg/* &
#for executing dwm

# execute the installer on startup
st -e sh -c "zsh $HOME/Installation.zsh" &
exec dwm
